@php
    $documentControl = (array) ($report['document_control'] ?? []);
    $reportSignatories = (array) ($report['signatories'] ?? []);
    $generatedAt = $documentControl['generated_at'] ?? ($report['generated_at'] ?? now('Asia/Manila'));
@endphp

@once
    <style>
        .report-signatories {
            margin-top: 24px;
            break-inside: avoid;
            page-break-inside: avoid;
            font-family: Arial, Helvetica, sans-serif;
            color: #0f172a;
        }
        .report-signatories__grid {
            display: grid;
            grid-template-columns: repeat(3, minmax(0, 1fr));
            gap: 24px;
        }
        .report-signatories__item { min-height: 92px; text-align: center; }
        .report-signatories__label {
            margin-bottom: 28px;
            font-size: 8px;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: .05em;
            color: #475569;
        }
        .report-signatories__name {
            border-top: 1px solid #475569;
            padding-top: 5px;
            font-size: 9px;
            font-weight: 700;
        }
        .report-signatories__position,
        .report-signatories__office {
            margin-top: 2px;
            font-size: 7px;
            color: #64748b;
        }
        .report-document-control {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            gap: 8px 18px;
            margin-top: 15px;
            border-top: 1px solid #cbd5e1;
            padding-top: 7px;
            font-size: 6.8px;
            line-height: 1.4;
            color: #64748b;
        }
        .report-document-control strong { color: #334155; }
        @media print {
            .report-signatories { margin-top: 18px; }
        }
    </style>
@endonce

@if ($reportSignatories !== [])
    <div class="report-signatories" aria-label="Official report signatories">
        <div class="report-signatories__grid">
            @foreach ($reportSignatories as $signatory)
                <div class="report-signatories__item">
                    <div class="report-signatories__label">{{ $signatory['label'] }}</div>
                    <div class="report-signatories__name">{{ $signatory['display_name'] }}</div>
                    <div class="report-signatories__position">{{ $signatory['display_position'] }}</div>
                    @if (($signatory['office'] ?? '') !== '')
                        <div class="report-signatories__office">{{ $signatory['office'] }}</div>
                    @endif
                </div>
            @endforeach
        </div>

        <div class="report-document-control">
            <span><strong>Reference:</strong> {{ $documentControl['reference'] ?? '—' }}</span>
            <span><strong>Document Version:</strong> {{ $documentControl['version_label'] ?? 'v1.0 · Rev 0' }}</span>
            <span><strong>Generated by:</strong> {{ $documentControl['generated_by'] ?? 'System-generated' }}</span>
            <span><strong>Generated:</strong> {{ $generatedAt->format('M d, Y h:i A') }}</span>
            <span><strong>Classification:</strong> {{ $documentControl['classification'] ?? 'Internal Government Report' }}</span>
        </div>
    </div>
@endif
