<?php

namespace App\Http\Controllers;

use App\Models\Adl;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AdlAllocationController extends Controller
{
    public function store(Request $request, Adl $adl): RedirectResponse
    {
        $validated = $request->validate([
            /*
            |--------------------------------------------------------------------------
            | Focal-owned Sponsor / Partner Reference
            |--------------------------------------------------------------------------
            |
            | These values are encoded in the ADL breakdown and become reusable
            | dropdown choices for the TUPAD Coordinator during Project Create.
            |
            */

            'fund_sponsor' => [
                'nullable',
                'string',
                'max:255',
            ],

            'partner' => [
                'nullable',
                'string',
                'max:255',
            ],

            'local_chief_executive_partylist' => ['nullable', 'string', 'max:255'],

            /*
            |--------------------------------------------------------------------------
            | Allocation Scope
            |--------------------------------------------------------------------------
            |
            | Province is the minimum geographic scope for an ADL allocation.
            | District and municipality are optional because an allocation may cover
            | an entire province. The legacy location display value is generated by
            | the server from these structured fields instead of being typed manually.
            |
            */
            'province' => ['required', 'string', 'max:150'],
            'district' => ['nullable', 'string', 'max:100'],
            'municipality' => ['nullable', 'string', 'max:150'],

            'grant_amount' => ['required', 'numeric', 'gt:0'],
            'admin_cost_amount' => ['nullable', 'numeric', 'min:0'],
            'remarks' => ['nullable', 'string', 'max:2000'],
        ]);

        $fundSponsor = $this->nullableTrimmedString($validated['fund_sponsor'] ?? null);
        $partner = $this->nullableTrimmedString($validated['partner'] ?? null);
        $lcePartyList = $this->nullableTrimmedString($validated['local_chief_executive_partylist'] ?? null);
        $province = trim($validated['province']);
        $district = $this->nullableTrimmedString($validated['district'] ?? null);
        $municipality = $this->nullableTrimmedString($validated['municipality'] ?? null);
        $remarks = $this->nullableTrimmedString($validated['remarks'] ?? null);

        $location = collect([
            $municipality,
            $district,
            $province,
        ])->filter()->implode(', ');

        $grants = round((float) $validated['grant_amount'], 2);
        $admin = round((float) ($validated['admin_cost_amount'] ?? 0), 2);
        $total = $grants + $admin;

        return DB::transaction(function () use (
            $request,
            $total,
            $grants,
            $admin,
            $adl,
            $fundSponsor,
            $partner,
            $lcePartyList,
            $location,
            $province,
            $district,
            $municipality,
            $remarks,
        ) {
            $lockedAdl = Adl::query()->lockForUpdate()->findOrFail($adl->id);
            $adjustedGrants = (float) $lockedAdl->grants + (float) $lockedAdl->realignments()->sum('amount');
            $allocated = (float) $lockedAdl->allocations()->sum('amount');
            $remaining = $adjustedGrants - $allocated;

            if ($grants > $remaining) {
                return back()->withInput()->withErrors([
                    'grant_amount' => sprintf('Grant allocation exceeds the remaining grant balance. Available grants: ₱%s.', number_format($remaining, 2)),
                ]);
            }

            $lockedAdl->allocations()->create([
                /*
                |--------------------------------------------------------------------------
                | Sponsor / Partner Reference
                |--------------------------------------------------------------------------
                |
                | Focal owns the official reusable values at ADL allocation level.
                | Project records still store their own final text snapshot.
                |
                */
                'fund_sponsor' => $fundSponsor,
                'partner' => $partner,
                'local_chief_executive_partylist' => $lcePartyList,

                // Generated from structured allocation scope; never trust a manual display string.
                'location' => $location,
                'province' => $province,
                'district' => $district,
                'municipality' => $municipality,

                // Keep the legacy amount column as the grant amount for compatibility with existing project budget logic.
                'amount' => $grants,
                'grant_amount' => $grants,
                'admin_cost_amount' => $admin,
                'total_amount' => $total,
                'remarks' => $remarks,
                'created_by' => $request->user()->id,
            ]);

            return redirect()->route('adl.show', $lockedAdl)->with('success', 'Fund allocation recorded successfully.');
        });
    }

    private function nullableTrimmedString(mixed $value): ?string
    {
        if (! is_string($value)) {
            return null;
        }

        $value = trim($value);

        return $value === '' ? null : $value;
    }
}
