@extends('layouts.app')
@section('title', 'PER ADL (Current)')
@section('content')
<div class="mb-5 flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h1 class="text-2xl font-bold text-slate-900">PER ADL (Current)</h1><p class="mt-1 text-sm text-slate-500">Focal fund monitoring aligned with the FY2025 workbook. Calculated columns are generated from the official project workflow.</p></div><form method="GET" class="flex gap-2"><select name="adl_id" class="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm"><option value="">All ADLs</option>@foreach($adls as $adl)<option value="{{ $adl->id }}" @selected(request('adl_id')==$adl->id)>{{ $adl->adl_number }}</option>@endforeach</select><button class="h-10 rounded-lg bg-[#063b86] px-4 text-sm font-semibold text-white">Filter</button></form></div>
<x-page-alerts />
<div class="rounded-xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-[3300px] w-full text-[11px]"><thead class="bg-[#ffe49a] text-[#172b4d]"><tr>
@foreach(['ADL No.','Fund Sponsor','LCE / Party-list','Province','District','City / Municipality','Alloc Grants','Admin Cost','Alloc Total','Realignment Grants','Date / No. MAF','Target Grants','Target Ben.','Obligated Grants','%','Wages','PPE','Insurance','Ben. Total','Female','Unutilized','IMSD / Payment','Implemented / Post-Docs','Ongoing Implementation','With NTP / For Implementation','Approved','For Approval','Under Evaluation','Available Balance','Remaining','Unused','Remarks','Action'] as $h)<th class="whitespace-nowrap border-r border-[#e7c96e] p-3 text-left font-bold">{{ $h }}</th>@endforeach
</tr></thead><tbody class="divide-y divide-slate-100">@forelse($rows as $r)<tr class="hover:bg-blue-50/30"><td class="p-3 font-bold text-[#063b86]">{{ $r['adl_number'] }}</td><td class="p-3">{{ $r['fund_sponsor'] }}</td><td class="p-3">{{ $r['lce_partylist'] }}</td><td class="p-3">{{ $r['province'] ?: '—' }}</td><td class="p-3">{{ $r['district'] ?: '—' }}</td><td class="p-3">{{ $r['municipality'] ?: '—' }}</td>
@foreach(['allocation_grants','allocation_admin_cost','allocation_total','realignment_grants'] as $k)<td class="p-3 text-right">₱{{ number_format($r[$k],2) }}</td>@endforeach<td class="p-3">{{ $r['maf'] ?: '—' }}</td><td class="p-3 text-right">₱{{ number_format($r['target_grants'],2) }}</td><td class="p-3 text-right">{{ number_format($r['target_beneficiaries']) }}</td><td class="p-3 text-right">₱{{ number_format($r['obligated_grants'],2) }}</td><td class="p-3 text-right font-semibold">{{ number_format($r['utilization'],2) }}%</td>
@foreach(['wages','ppe','insurance'] as $k)<td class="p-3 text-right">₱{{ number_format($r[$k],2) }}</td>@endforeach<td class="p-3 text-right">{{ number_format($r['beneficiaries']) }}</td><td class="p-3 text-right">{{ number_format($r['female']) }}</td>
@foreach(['unutilized','for_payment','post_docs','ongoing_implementation','for_implementation','approved','for_approval','under_evaluation','available_balance','remaining','unused'] as $k)<td class="p-3 text-right">₱{{ number_format($r[$k],2) }}</td>@endforeach<td class="p-3 max-w-[220px]">{{ $r['remarks'] ?: '—' }}</td><td class="p-3"><a href="{{ route('adl.show',$r['adl_id']) }}" class="font-semibold text-[#063b86]">Manage ADL</a></td></tr>@empty<tr><td colspan="33" class="p-10 text-center text-slate-400">No monitoring rows found.</td></tr>@endforelse</tbody></table></div></div>
@endsection
